### PR TITLE
Improve type specs, add dialyzer and update deps

### PR DESCRIPTION
**Pull request by vtm9**

### CODE REVIEW

**Comment by zven21** [comment]
thank you for your pr

**Comment by vtm9** [comment]
@zven21 , what do you think about dialyzer?

**Comment by vtm9** [comment]
@zven21 maybe add dialyzer task to `travis CI`?

**Comment by zven21** [comment]
@vtm9 I just looked at the dialyzer doc, this's great, I think I can add it to travis CI.

**Comment by vtm9** [comment]
Nice,   so let's merge the PR?

**Comment by zven21** [comment]
@vtm9 OK, Why my `mix dialyzer ` command is running for 10 minutes, it’s not over yet.

**Comment by zven21** [comment]
@vtm9 it's finished. 😄

**Comment by vtm9** [comment]
@zven21 Thx. You should add cache plt to travis, then it will be faster next time

**Pull request merged**
